# -*- coding: utf-8 -*-
{
    'name': "Tianguis_Guadalajara",
    'summary': "Sistema de tianguis de la ciudad de Guadalajara",
    'description': "",
    'author': "PGM",
    'version': '0.1',
    # any module necessary for this one to work correctly
    'depends': ['base', 'web', 'report',],
    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
        'views/layouts/menus_view.xml',
        #'views/tianguis/asistencias_view.xml',
        'views/tianguis/c_administrador_view.xml',
        'views/tianguis/c_recaudador_view.xml',
        'views/tianguis/c_calles_views.xml',
        'views/tianguis/c_colonias_view.xml',
        'views/tianguis/c_permisionario_view.xml',
        'views/tianguis/c_tianguis_view.xml',
        'views/tianguis/puestos_view.xml',
        'views/tianguis/c_calles_tianguis.xml',
        # 'views/facturas_view.xml',
        'views/tianguis/h_movimiento_puesto_view.xml',
        #'views/tianguis/lista_pierde_lugar_view.xml',
        # 'views/tarjeton_view.xml',
        'views/tianguis/c_familias_giros_view.xml',
        'views/tianguis/c_giros_comerciales_view.xml',
        'views/tianguis/c_usuarios_view.xml',
        'views/tianguis/c_mvto_desc.xml',
        'views/tianguis/fotos_view.xml',
        'views/tianguis/bitacora_view.xml',
        #'views/tianguis/pagos_view.xml',
        'views/tianguis/r_apercibimientos_view.xml',
        #'views/tianguis/lista_espera_view.xml',
        'views/espacios_abiertos/c_solicitantes_view.xml',
        'views/espacios_abiertos/permisos_view.xml',
        'views/reportes.xml',
        'views/rcredencial_view.xml',
        'views/tianguis/pruebas.xml',
        'views/tianguis/c_zonatianguis_view.xml',
        'report/informe_general.xml',
        'report/giros_comerciales.xml',
        'report/puestos_permisionario.xml',
        'views/rtarjeton_view.xml',
        'views/festividades/c_festividades_view.xml',
        'views/festividades/c_permisionario_view.xml',
        'views/festividades/fpuesto_view.xml',
        'views/espacios_abiertos/puestos_espacios_view.xml',
        'views/festividades/c_juegos_view.xml',
        'views/festividades/c_comercio_view.xml',
        'views/festividades/c_lugar_view.xml',
        'report/permisionario_permiso.xml',
        'report/tarjetones_fotografia.xml',
        'report/pagos_tianguis.xml',
        'views/tianguis/r_tianguis_racaudado_view.xml',
        'report/recaudacion_tianguis.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
